In [1]:
import numpy as np

In [16]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get Dimension
a.ndim

1

In [9]:
# Get Shape
b.shape

(2, 3)

In [18]:
# Get Type

a.dtype

dtype('int32')

In [17]:
# Get Size

a.itemsize

4

In [21]:
# Get total size

a.nbytes   # a.size * a.itemsize

12

## Accesing/Changing specific elements,rows,columns etc

In [24]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
# Get a specific element [row, column] | python starts with 0

a[1, 5] # 1 > means 2nd row



13

In [26]:
a[1, -2]

13

In [28]:
# Get a specific row

a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
# Get a specific column

a[: , 2]

array([ 3, 10])

In [30]:
# Getting little more fancy [startindex:endindex:stepsize]

a[0, 1:6:2]   # 1.satır, 2.startindex:6.endindex:2atlama

array([2, 4, 6])

In [32]:
a[0, 1:-1:1]

array([2, 3, 4, 5, 6])

In [33]:
a[1,5] = 20
print(a)    # 2.satır 6.sütundaki değer değiştirildi

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [36]:
a[:,2] = [5]   #3.sütun komple 5 yapıldı
print(a)


[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [38]:
a[:,2] = [1,2]   #3.sütuna yeni değerler [1,2] atandı
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


##### *3-d example

In [40]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
#Get specific element (work ouside in)

b[0,1,1]

4

In [48]:
#replace

b[:,1,:] = [[9,9],[8,8]]

In [49]:
b[:,1,:]

array([[9, 9],
       [8, 8]])

## Initalizing Different Types of Arrays

In [50]:
# All 0's matrix

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [53]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
# all 1's matrix

np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [56]:
# Any other number

np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [57]:
#Any other number (full_like)

np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [58]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [61]:
#Random decimal numbers

np.random.rand(4,2,3)

array([[[0.77701224, 0.29280011, 0.3090872 ],
        [0.14905106, 0.18059573, 0.07720221]],

       [[0.0466189 , 0.26665338, 0.94303861],
        [0.16026377, 0.92097361, 0.37459534]],

       [[0.94288608, 0.80740266, 0.94112353],
        [0.70014482, 0.29637655, 0.99964238]],

       [[0.40917318, 0.24280677, 0.79297202],
        [0.53685404, 0.04480032, 0.72779393]]])

In [68]:
#Random int values

np.random.randint(-2,7, size=(3,3))

array([[ 5, -2,  4],
       [-1,  5, -2],
       [ 4,  4,  6]])

In [69]:
#The identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
#Repeat an array

arr = np.array([[1,2,3]])       #<<<< 2 parantez oldugu için 2 dimension
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [82]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [86]:
matrix = np.ones((5,5))
matrix[1:4,1:4] = 0
matrix[2,2] = 9

print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!

In [88]:
a = np.array([1,2,3])
b = a
b[0] = 100

print(a)

[100   2   3]


In [89]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [91]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [92]:
a + 2

array([3, 4, 5, 6])

In [93]:
a - 2

array([-1,  0,  1,  2])

In [94]:
a * 2

array([2, 4, 6, 8])

In [95]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [96]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [97]:
a ** 2

array([ 1,  4,  9, 16])

In [101]:
# Take the sin

np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [102]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

#### Lineer Algebra

In [107]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [109]:
#Find the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://numpy.org/doc/stable/reference/routines.linalg.html)
# Determinant
# Trace
# Singular vector decomposition
# Eigenvalues
# matrix norm
# Inverse
# etc..

#### Statistics

In [110]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
np.min(stats,axis=1)

array([1, 4])

In [117]:
np.max(stats, axis=1) 

array([3, 6])

In [118]:
np.sum(stats)  #totals of all elements

21

In [119]:
np.sum(stats,axis=0) #column totals 

array([5, 7, 9])

In [120]:
np.sum(stats,axis=1) #row totals 

array([ 6, 15])

#### Reorganizing Arrays

In [121]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)



[[1 2 3 4]
 [5 6 7 8]]


In [123]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [124]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [128]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [133]:
# Horizontal stacking vectors

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous

#### Load data from file

In [161]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[   1    2    3    4    5    6    7    8   98    9    3   12  312 3123
    13    2    2    3]
 [   3  443    2    2   34    6    8    8    2    1   23   15    6    7
     9   12   13   15]
 [   4    5   22   57    8    9  343   21   23    4   77    9    5   43
     1    2    3    4]]


#### Boolean Masking and Advanced Indexing

In [160]:
filedata > 50

array([[False, False, False, False, False, False, False, False,  True,
        False, False, False,  True,  True, False, False, False, False],
       [False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False,  True, False, False,  True, False, False,
        False,  True, False, False, False, False, False, False, False]])

In [162]:
filedata[filedata > 50]

array([  98,  312, 3123,  443,   57,  343,   77])

In [164]:
## You can index with a list in NumPy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [165]:
np.any(filedata > 50, axis=0)  #column based checking values if any value greater than 50 its True

array([False,  True, False,  True, False, False,  True, False,  True,
       False,  True, False,  True,  True, False, False, False, False])

In [166]:
np.all(filedata > 50, axis=0)  #column based checking values must be all values greater than 50 its True

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [167]:
np.all(filedata > 50, axis=1) #row based checking values must be all values greater than 50 its True

array([False, False, False])

In [168]:
np.any(filedata > 50, axis=1)  #row based checking values if any value greater than 50 its True

array([ True,  True,  True])

In [170]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False, False,
        False,  True, False, False, False, False, False, False, False]])

In [173]:
(~((filedata > 50) & (filedata < 100)))  #reversed (~ means NOT)

array([[ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True]])

In [200]:
#### Mini Quiz

a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [201]:
 # find 3rd-4th row 1-2column

a[2:4,0:2]  

array([[11, 12],
       [16, 17]])

In [199]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [215]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])